### PR TITLE
Added support of bucket operations in CORIO

### PR DESCRIPTION
**Pull request by priyankaborawake**
Signed-off-by: priyanka.borawake <priyanka.borawake@seagate.com>

# Problem Statement
-  Added support of bucket operations in CORIO

# Design
-  For Bug, Describe the fix here.
-  For new test addition post the link for design

# Coding
   Checklist for Author
-  [x] Coding conventions are followed and code is formatted (e.g. using pycharm in-built formatter)

# Testing 
  Checklist for Author
-  [ ] New/Affected tests are executed
-  [ ] Attach test execution logs

# Review Checklist 
  Checklist for Author
-  [ ] JIRA number/GitHub Issue added to PR
-  [ ] PR is self reviewed
-  [ ] Jira and state/status is updated and JIRA is updated with PR link
-  [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
-  [ ] Changes done to ReadMe

### CODE REVIEW

**Comment by ketanarlulkar** [comment]
Update your branch/resolve conflicts

**Review by ketanarlulkar — APPROVED** [review]

**Review by VikasKumarC — APPROVED** [review]

**Comment by VikasKumarC** [comment]
@DhobaleVishal  Review and Merge

**Review by DhobaleVishal — COMMENTED** [review]
@priyankaborawake Please fix codacy issues.

**Comment by VikasKumarC** [comment]
@priyankaborawake  Please fix codacy issues

**Comment by priyankaborawake** [comment]
> @priyankaborawake Please fix codacy issues.

@DhobaleVishal Fixed codacy issues

**Pull request merged**
